import styled from "styled-components";
import { colors } from "../../styles/colors";

export const Main = styled.div`
display:flex;
flex-direction:column;
height:100vh;
  header{
    color:${colors.white};
    h1{
      font-size:38px;
      text-align:center;
    }
    flex:1;
  }
  #main{
    flex:6;
    display:flex;
    flex-wrap: wrap;
    .folder{
      cursor:pointer;
      margin-left:24px;
      width:120px;
      height:120px;
      display:flex;
      align-items:center;
      flex-direction:column;
      img{
        object-fit:contain;
        width:80px;
      }
      p{
        text-align:center;
        text-shadow:4px 4px 5px black;
        color:${colors.white};
        font-size:16px;
        width:100%;
      }
    }
    .activated{
      background-image:linear-gradient(to bottom ,${colors.lightGreen},${colors.mediumGreen}, ${colors.darkGreen});
    }
  }
  #menuWrapper{
    position: absolute;
    top:0;
    left:0;
    right:0;
    bottom:0;
    z-index:10;   
    #menu{
      box-shadow:4px 4px 5px black;
      position:absolute;
      background-color:${colors.white};
      width:220px;
      height:240px;
      display:flex;
      flex-direction:column;
      .disable{
        color:gray;
        pointer-events:none;
      }
      p{
        margin-top:8px;
        padding-left:4px;
        cursor:pointer;
        &:hover{
          background-color:${colors.darkPink};
          color:white;
        }
      &:last-child{
        margin-top:auto;
      }
      }
    }
  }
  #createFolder{
    position:absolute;
    height:100vh;
    width:100%;
    background-color:rgba(0,0,0,0.4);
    display:flex;
    justify-content:center;
    align-items:center;
    div{
      border-radius:4px;
      display:flex;
      flex-direction:column;
      justify-content:center;
      align-items:center;
      background-color:${colors.mediumPurple};
     
      img{
        object-fit:contain;
        width:200px;
      }
    }
    #inputWrapper{
        height:200px;
        position: relative;
        width:200px;
        span{
          position:absolute;
          background-color:rgba(0,0,0,0.4);
          height:200px;
          width:200px;
          display:flex;
          justify-content:center;
          align-items:center;
          color:white;
          opacity:0;
          z-index:11;
          pointer-events:none;
        }
        img{
          position:absolute;
          object-fit:contain;
          max-width:200px;
          height:200px;
          pointer-events:none;
          left:0;
          z-index:10;
        }
        input{
          position:absolute;
          background-color:blue;
          height:200px;
          width:200px;
          cursor:pointer;
          opacity:0;
        }
      }
    #wrapperActions{
      display:flex;
      width:100%;
      justify-content:space-evenly;
      flex-direction:row;      
      button{
        border:none;
        width:40%;
        border-radius:4px;
        background-color:${colors.lightBlue};
      }
    }
  }
`;
