import styled from "styled-components";
import { colors } from "../../styles/colors";

export const Main = styled.div`
  height:100vh;
  display:grid;
  grid-template-columns: 2fr 1fr;
  #list{
    grid-column:1/2;
    background-color:white;
    height:100vh;
    overflow-y:scroll;
    #header{
      display:flex;

      z-index:100;
      justify-content:space-evenly;
      align-items:center;
      height:auto;
      cursor:auto;
      #add{
        cursor:pointer;      
        background-color:${colors.mediumPurple};
        border-radius:4px;
        border:none;
        color:white;
        width:150px;
        height:40px;
        &:hover{
          background-color:${colors.lightBlue};
          box-shadow:4px 4px 2px ${colors.lightBlue};
        }
      }
      #inputWrapper{
        height:100px;
        position: relative;
      
        span{
          position:absolute;
          background-color:rgba(0,0,0,0.4);
          height:100px;
          width:100px;
          display:flex;
          justify-content:center;
          align-items:center;
          color:white;
          opacity:0;
          z-index:11;
          pointer-events:none;
        }
        img{
          position:absolute;
          object-fit:contain;
          max-width:100px;
          height:100px;
          pointer-events:none;
          left:0;
          z-index:10;
        }
        input{
          position:absolute;
          background-color:blue;
          height:100px;
          width:100px;
          cursor:pointer;
          opacity:0;
        }
      }
    }
    #item{
      height:50px;
      display:flex;
      justify-content:space-between;
      align-items:center;
      padding-left:24px;
      padding-right:24px;
      cursor:pointer;
      &:nth-child(even){
        background-color:${colors.lightGreen};
      }
      &:hover{
        background-color:${colors.lightBlue}
      }
      button{
        cursor:pointer;
        background-color:${colors.darkPink};
        border:none;
        border-radius:4px;
        color:white;
        width:100px;
        height:40px;
        &:hover{
          background-color:${colors.mediumPink};
          box-shadow:4px 4px 2px ${colors.darkPink} !important;
        }
      }
    
    }
   
  }
  #edit{
    grid-column:2/3;
    display:flex;
    justify-content:space-evenly;
    align-items:center;
    flex-direction:column;
    img{
      object-fit:contain;
      width:200px;
      max-height:200px;
    }
    input{
      width:80%;
    }
    .update{
      cursor:pointer;
      background-color:${colors.lightBlue};
      border:none;
      border-radius:4px;
      color:white;
      width:200px;
      height:40px;
    }
    .disable{
      color:gray;
      pointer-events:none;
      width:200px;
      height:40px;
    }
  }
  #create{
    position:absolute;
    top:0;
    bottom:0;
    left:0;
    right:0;
    display:flex;
    justify-content:center;
    align-items:center;
    flex-direction:column;
    background-color:rgba(0,0,0,0.4);
    #wrapper{
      border-radius:8px;
      background-image:linear-gradient(to right, ${colors.lightBlue}, ${colors.lightGreen});
      display:flex;
      height:400px;
      justify-content:space-evenly;
      align-items:center;
      flex-direction:column;
      img{
        object-fit:contain;
        width:200px;
        max-height:200px;
      }
      div{
        display:flex;
        width:100%;
        justify-content:space-evenly;
      }
    }
  }
`;
